# Generated bytecode-binding modules emitted by Mix.Tasks.Cartouche.Gen.
# Mirrors `.doctor.exs`'s `ignore_paths: [~r"^lib/cartouche/contract/"]`.
#
# TODO(Task 42): drop these once the generator's `decode_error/1` /
# `decode_call/1` / `decode_event/2` `if true ... else ... end` fallbacks
# are fixed and IConsole is regenerated — that's the source of the
# `pattern can never match the type true` flood.
# TODO(Task 41): same — generator's bytecode-flag separation
# (init vs deployed) eliminates the `exec_vm_*` / undefined-function
# warnings on asymmetric-bytecode shapes.
# TODO(Task 44): gating coverage push on `Mix.Tasks.Cartouche.Gen`
# blocks both 41 and 42; once those land and IConsole is regenerated,
# remove this file and the `dialyzer:` config line in mix.exs.
[
  {"lib/cartouche/contract/i_console.ex"},
  {"lib/cartouche/contract/sleuth.ex"}
]
