%Doctor.Config{
  # Mix.Tasks.Cartouche.Gen builds AST literals via `def unquote(name)(args)`
  # inside `quote do ... end` blocks for the contract modules it emits. Doctor's
  # source-level AST walker counts those literals as if they were defs of the
  # Mix task itself (BEAM introspection confirms only run/1 is actually exported),
  # producing 23 false-positive missing-doc warnings. Excluding the module silences
  # the false positive; the @moduledoc stays in source for `mix help cartouche.gen`.
  # TODO: drop once Doctor's AST walker handles `def unquote(name)(args)` inside
  # `quote do ... end` blocks (not currently tracked in ROADMAP — upstream Doctor
  # limitation).
  ignore_modules: [Mix.Tasks.Cartouche.Gen],
  # Generated bytecode-binding modules under lib/cartouche/contract/ — same
  # directory excluded by `.dialyzer_ignore.exs`. Generator currently emits no
  # @doc/@spec on the functions it builds.
  # TODO(Task 50): drop this exclusion once `Mix.Tasks.Cartouche.Gen` emits
  # `@doc`/`@spec` on generated bindings and IConsole is regenerated. Natural
  # co-deliverable with Task 42 (template fix → IConsole regeneration).
  ignore_paths: [~r"^lib/cartouche/contract/"],
  min_module_doc_coverage: 100,
  min_module_spec_coverage: 100,
  min_overall_doc_coverage: 100,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 100,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false,
  failed: false
}
