defmodule Cartouche.Contract.IERC20 do
  @moduledoc false
  # Auto-generated bytestring topic-0 hashes wrap to >120 chars after `mix format`;
  # the formatter is authoritative for generated test fixtures.
  # credo:disable-for-this-file Credo.Check.Readability.MaxLineLength
  use Cartouche.Hex

  alias Cartouche.Transaction.V2

  @doc false
  @spec contract_name() :: term()
  def contract_name do
    "IERC20"
  end

  @doc false
  @spec allowance_selector() :: term()
  def allowance_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "allowance",
      function_type: :function,
      returns: [%{name: "", type: {:uint, 256}}],
      state_mutability: :view,
      types: [%{name: "owner", type: :address}, %{name: "spender", type: :address}]
    }
  end

  @doc false
  @spec encode_allowance(term(), term()) :: term()
  def encode_allowance(owner, spender) do
    ABI.encode(allowance_selector(), [owner, spender])
  end

  @doc false
  @spec prepare_allowance(term(), term(), term(), term()) :: term()
  def prepare_allowance(contract, owner, spender, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_allowance(owner, spender), opts)
  end

  @doc false
  @spec build_trx_allowance(term(), term(), term()) :: term()
  def build_trx_allowance(contract, owner, spender) do
    %V2{destination: contract, data: encode_allowance(owner, spender)}
  end

  @doc false
  @spec call_allowance(term(), term(), term(), term()) :: term()
  def call_allowance(contract, owner, spender, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_allowance(contract, owner, spender), opts)
  end

  @doc false
  @spec estimate_gas_allowance(term(), term(), term(), term()) :: term()
  def estimate_gas_allowance(contract, owner, spender, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_allowance(contract, owner, spender), opts)
  end

  @doc false
  @spec execute_allowance(term(), term(), term(), term()) :: term()
  def execute_allowance(contract, owner, spender, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_allowance(owner, spender), opts)
  end

  @doc false
  @spec decode_allowance_call(term()) :: term()
  def decode_allowance_call(<<221, 98, 237, 62>> <> calldata) do
    _signature = hex!("0xdd62ed3e")
    ABI.decode(allowance_selector(), calldata)
  end

  @doc false
  @spec approve_selector() :: term()
  def approve_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "approve",
      function_type: :function,
      returns: [%{name: "", type: :bool}],
      state_mutability: :nonpayable,
      types: [%{name: "spender", type: :address}, %{name: "amount", type: {:uint, 256}}]
    }
  end

  @doc false
  @spec encode_approve(term(), term()) :: term()
  def encode_approve(spender, amount) do
    ABI.encode(approve_selector(), [spender, amount])
  end

  @doc false
  @spec prepare_approve(term(), term(), term(), term()) :: term()
  def prepare_approve(contract, spender, amount, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_approve(spender, amount), opts)
  end

  @doc false
  @spec build_trx_approve(term(), term(), term()) :: term()
  def build_trx_approve(contract, spender, amount) do
    %V2{destination: contract, data: encode_approve(spender, amount)}
  end

  @doc false
  @spec call_approve(term(), term(), term(), term()) :: term()
  def call_approve(contract, spender, amount, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_approve(contract, spender, amount), opts)
  end

  @doc false
  @spec estimate_gas_approve(term(), term(), term(), term()) :: term()
  def estimate_gas_approve(contract, spender, amount, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_approve(contract, spender, amount), opts)
  end

  @doc false
  @spec execute_approve(term(), term(), term(), term()) :: term()
  def execute_approve(contract, spender, amount, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_approve(spender, amount), opts)
  end

  @doc false
  @spec decode_approve_call(term()) :: term()
  def decode_approve_call(<<9, 94, 167, 179>> <> calldata) do
    _signature = hex!("0x095ea7b3")
    ABI.decode(approve_selector(), calldata)
  end

  @doc false
  @spec balance_of_selector() :: term()
  def balance_of_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "balanceOf",
      function_type: :function,
      returns: [%{name: "", type: {:uint, 256}}],
      state_mutability: :view,
      types: [%{name: "account", type: :address}]
    }
  end

  @doc false
  @spec encode_balance_of(term()) :: term()
  def encode_balance_of(account) do
    ABI.encode(balance_of_selector(), [account])
  end

  @doc false
  @spec prepare_balance_of(term(), term(), term()) :: term()
  def prepare_balance_of(contract, account, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_balance_of(account), opts)
  end

  @doc false
  @spec build_trx_balance_of(term(), term()) :: term()
  def build_trx_balance_of(contract, account) do
    %V2{destination: contract, data: encode_balance_of(account)}
  end

  @doc false
  @spec call_balance_of(term(), term(), term()) :: term()
  def call_balance_of(contract, account, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_balance_of(contract, account), opts)
  end

  @doc false
  @spec estimate_gas_balance_of(term(), term(), term()) :: term()
  def estimate_gas_balance_of(contract, account, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_balance_of(contract, account), opts)
  end

  @doc false
  @spec execute_balance_of(term(), term(), term()) :: term()
  def execute_balance_of(contract, account, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_balance_of(account), opts)
  end

  @doc false
  @spec decode_balance_of_call(term()) :: term()
  def decode_balance_of_call(<<112, 160, 130, 49>> <> calldata) do
    _signature = hex!("0x70a08231")
    ABI.decode(balance_of_selector(), calldata)
  end

  @doc false
  @spec decimals_selector() :: term()
  def decimals_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "decimals",
      function_type: :function,
      returns: [%{name: "", type: {:uint, 8}}],
      state_mutability: :view,
      types: []
    }
  end

  @doc false
  @spec encode_decimals() :: term()
  def encode_decimals do
    ABI.encode(decimals_selector(), [])
  end

  @doc false
  @spec prepare_decimals(term(), term()) :: term()
  def prepare_decimals(contract, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_decimals(), opts)
  end

  @doc false
  @spec build_trx_decimals(term()) :: term()
  def build_trx_decimals(contract) do
    %V2{destination: contract, data: encode_decimals()}
  end

  @doc false
  @spec call_decimals(term(), term()) :: term()
  def call_decimals(contract, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_decimals(contract), opts)
  end

  @doc false
  @spec estimate_gas_decimals(term(), term()) :: term()
  def estimate_gas_decimals(contract, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_decimals(contract), opts)
  end

  @doc false
  @spec execute_decimals(term(), term()) :: term()
  def execute_decimals(contract, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_decimals(), opts)
  end

  @doc false
  @spec decode_decimals_call(term()) :: term()
  def decode_decimals_call(<<49, 60, 229, 103>> <> calldata) do
    _signature = hex!("0x313ce567")
    ABI.decode(decimals_selector(), calldata)
  end

  @doc false
  @spec name_selector() :: term()
  def name_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "name",
      function_type: :function,
      returns: [%{name: "", type: :string}],
      state_mutability: :view,
      types: []
    }
  end

  @doc false
  @spec encode_name() :: term()
  def encode_name do
    ABI.encode(name_selector(), [])
  end

  @doc false
  @spec prepare_name(term(), term()) :: term()
  def prepare_name(contract, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_name(), opts)
  end

  @doc false
  @spec build_trx_name(term()) :: term()
  def build_trx_name(contract) do
    %V2{destination: contract, data: encode_name()}
  end

  @doc false
  @spec call_name(term(), term()) :: term()
  def call_name(contract, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_name(contract), opts)
  end

  @doc false
  @spec estimate_gas_name(term(), term()) :: term()
  def estimate_gas_name(contract, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_name(contract), opts)
  end

  @doc false
  @spec execute_name(term(), term()) :: term()
  def execute_name(contract, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_name(), opts)
  end

  @doc false
  @spec decode_name_call(term()) :: term()
  def decode_name_call(<<6, 253, 222, 3>> <> calldata) do
    _signature = hex!("0x06fdde03")
    ABI.decode(name_selector(), calldata)
  end

  @doc false
  @spec symbol_selector() :: term()
  def symbol_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "symbol",
      function_type: :function,
      returns: [%{name: "", type: :string}],
      state_mutability: :view,
      types: []
    }
  end

  @doc false
  @spec encode_symbol() :: term()
  def encode_symbol do
    ABI.encode(symbol_selector(), [])
  end

  @doc false
  @spec prepare_symbol(term(), term()) :: term()
  def prepare_symbol(contract, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_symbol(), opts)
  end

  @doc false
  @spec build_trx_symbol(term()) :: term()
  def build_trx_symbol(contract) do
    %V2{destination: contract, data: encode_symbol()}
  end

  @doc false
  @spec call_symbol(term(), term()) :: term()
  def call_symbol(contract, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_symbol(contract), opts)
  end

  @doc false
  @spec estimate_gas_symbol(term(), term()) :: term()
  def estimate_gas_symbol(contract, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_symbol(contract), opts)
  end

  @doc false
  @spec execute_symbol(term(), term()) :: term()
  def execute_symbol(contract, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_symbol(), opts)
  end

  @doc false
  @spec decode_symbol_call(term()) :: term()
  def decode_symbol_call(<<149, 216, 155, 65>> <> calldata) do
    _signature = hex!("0x95d89b41")
    ABI.decode(symbol_selector(), calldata)
  end

  @doc false
  @spec total_supply_selector() :: term()
  def total_supply_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "totalSupply",
      function_type: :function,
      returns: [%{name: "", type: {:uint, 256}}],
      state_mutability: :view,
      types: []
    }
  end

  @doc false
  @spec encode_total_supply() :: term()
  def encode_total_supply do
    ABI.encode(total_supply_selector(), [])
  end

  @doc false
  @spec prepare_total_supply(term(), term()) :: term()
  def prepare_total_supply(contract, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_total_supply(), opts)
  end

  @doc false
  @spec build_trx_total_supply(term()) :: term()
  def build_trx_total_supply(contract) do
    %V2{destination: contract, data: encode_total_supply()}
  end

  @doc false
  @spec call_total_supply(term(), term()) :: term()
  def call_total_supply(contract, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_total_supply(contract), opts)
  end

  @doc false
  @spec estimate_gas_total_supply(term(), term()) :: term()
  def estimate_gas_total_supply(contract, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_total_supply(contract), opts)
  end

  @doc false
  @spec execute_total_supply(term(), term()) :: term()
  def execute_total_supply(contract, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_total_supply(), opts)
  end

  @doc false
  @spec decode_total_supply_call(term()) :: term()
  def decode_total_supply_call(<<24, 22, 13, 221>> <> calldata) do
    _signature = hex!("0x18160ddd")
    ABI.decode(total_supply_selector(), calldata)
  end

  @doc false
  @spec transfer_selector() :: term()
  def transfer_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "transfer",
      function_type: :function,
      returns: [%{name: "", type: :bool}],
      state_mutability: :nonpayable,
      types: [%{name: "to", type: :address}, %{name: "amount", type: {:uint, 256}}]
    }
  end

  @doc false
  @spec encode_transfer(term(), term()) :: term()
  def encode_transfer(to, amount) do
    ABI.encode(transfer_selector(), [to, amount])
  end

  @doc false
  @spec prepare_transfer(term(), term(), term(), term()) :: term()
  def prepare_transfer(contract, to, amount, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_transfer(to, amount), opts)
  end

  @doc false
  @spec build_trx_transfer(term(), term(), term()) :: term()
  def build_trx_transfer(contract, to, amount) do
    %V2{destination: contract, data: encode_transfer(to, amount)}
  end

  @doc false
  @spec call_transfer(term(), term(), term(), term()) :: term()
  def call_transfer(contract, to, amount, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_transfer(contract, to, amount), opts)
  end

  @doc false
  @spec estimate_gas_transfer(term(), term(), term(), term()) :: term()
  def estimate_gas_transfer(contract, to, amount, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_transfer(contract, to, amount), opts)
  end

  @doc false
  @spec execute_transfer(term(), term(), term(), term()) :: term()
  def execute_transfer(contract, to, amount, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_transfer(to, amount), opts)
  end

  @doc false
  @spec decode_transfer_call(term()) :: term()
  def decode_transfer_call(<<169, 5, 156, 187>> <> calldata) do
    _signature = hex!("0xa9059cbb")
    ABI.decode(transfer_selector(), calldata)
  end

  @doc false
  @spec transfer_from_selector() :: term()
  def transfer_from_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "transferFrom",
      function_type: :function,
      returns: [%{name: "", type: :bool}],
      state_mutability: :nonpayable,
      types: [
        %{name: "from", type: :address},
        %{name: "to", type: :address},
        %{name: "amount", type: {:uint, 256}}
      ]
    }
  end

  @doc false
  @spec encode_transfer_from(term(), term(), term()) :: term()
  def encode_transfer_from(from, to, amount) do
    ABI.encode(transfer_from_selector(), [from, to, amount])
  end

  @doc false
  @spec prepare_transfer_from(term(), term(), term(), term(), term()) :: term()
  def prepare_transfer_from(contract, from, to, amount, opts \\ []) do
    Cartouche.RPC.prepare_trx(contract, encode_transfer_from(from, to, amount), opts)
  end

  @doc false
  @spec build_trx_transfer_from(term(), term(), term(), term()) :: term()
  def build_trx_transfer_from(contract, from, to, amount) do
    %V2{destination: contract, data: encode_transfer_from(from, to, amount)}
  end

  @doc false
  @spec call_transfer_from(term(), term(), term(), term(), term()) :: term()
  def call_transfer_from(contract, from, to, amount, opts \\ []) do
    Cartouche.RPC.call_trx(build_trx_transfer_from(contract, from, to, amount), opts)
  end

  @doc false
  @spec estimate_gas_transfer_from(term(), term(), term(), term(), term()) :: term()
  def estimate_gas_transfer_from(contract, from, to, amount, opts \\ []) do
    Cartouche.RPC.estimate_gas(build_trx_transfer_from(contract, from, to, amount), opts)
  end

  @doc false
  @spec execute_transfer_from(term(), term(), term(), term(), term()) :: term()
  def execute_transfer_from(contract, from, to, amount, opts \\ []) do
    Cartouche.RPC.execute_trx(contract, encode_transfer_from(from, to, amount), opts)
  end

  @doc false
  @spec decode_transfer_from_call(term()) :: term()
  def decode_transfer_from_call(<<35, 184, 114, 221>> <> calldata) do
    _signature = hex!("0x23b872dd")
    ABI.decode(transfer_from_selector(), calldata)
  end

  @doc false
  @spec approval_event_selector() :: term()
  def approval_event_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "Approval",
      function_type: :event,
      returns: nil,
      state_mutability: nil,
      types: [
        %{indexed: true, name: "owner", type: :address},
        %{indexed: true, name: "spender", type: :address},
        %{indexed: false, name: "value", type: {:uint, 256}}
      ]
    }
  end

  @doc false
  @spec encode_approval_event(term(), term(), term()) :: term()
  def encode_approval_event(owner, spender, value) do
    ABI.encode(approval_event_selector(), [owner, spender, value])
  end

  @doc false
  @spec decode_approval_event(term(), term()) :: term()
  def decode_approval_event(topics, data) when is_list(topics) do
    _signature = hex!("0x8c5be1e5")
    ABI.Event.decode_event(data, topics, approval_event_selector())
  end

  @doc false
  @spec transfer_ddf252ad_event_selector() :: term()
  def transfer_ddf252ad_event_selector do
    %{
      __struct__: ABI.FunctionSelector,
      function: "Transfer",
      function_type: :event,
      returns: nil,
      state_mutability: nil,
      types: [
        %{indexed: true, name: "from", type: :address},
        %{indexed: true, name: "to", type: :address},
        %{indexed: false, name: "value", type: {:uint, 256}}
      ]
    }
  end

  @doc false
  @spec encode_transfer_ddf252ad_event(term(), term(), term()) :: term()
  def encode_transfer_ddf252ad_event(from, to, value) do
    ABI.encode(transfer_ddf252ad_event_selector(), [from, to, value])
  end

  @doc false
  @spec decode_transfer_ddf252ad_event(term(), term()) :: term()
  def decode_transfer_ddf252ad_event(topics, data) when is_list(topics) do
    _signature = hex!("0xddf252ad")
    ABI.Event.decode_event(data, topics, transfer_ddf252ad_event_selector())
  end

  @doc false
  @spec decode_call(term()) :: term()
  def decode_call(<<221, 98, 237, 62>> <> _ = calldata) do
    _signature = hex!("0xdd62ed3e")
    {:ok, "allowance", decode_allowance_call(calldata)}
  end

  def decode_call(<<9, 94, 167, 179>> <> _ = calldata) do
    _signature = hex!("0x095ea7b3")
    {:ok, "approve", decode_approve_call(calldata)}
  end

  def decode_call(<<112, 160, 130, 49>> <> _ = calldata) do
    _signature = hex!("0x70a08231")
    {:ok, "balanceOf", decode_balance_of_call(calldata)}
  end

  def decode_call(<<49, 60, 229, 103>> <> _ = calldata) do
    _signature = hex!("0x313ce567")
    {:ok, "decimals", decode_decimals_call(calldata)}
  end

  def decode_call(<<6, 253, 222, 3>> <> _ = calldata) do
    _signature = hex!("0x06fdde03")
    {:ok, "name", decode_name_call(calldata)}
  end

  def decode_call(<<149, 216, 155, 65>> <> _ = calldata) do
    _signature = hex!("0x95d89b41")
    {:ok, "symbol", decode_symbol_call(calldata)}
  end

  def decode_call(<<24, 22, 13, 221>> <> _ = calldata) do
    _signature = hex!("0x18160ddd")
    {:ok, "totalSupply", decode_total_supply_call(calldata)}
  end

  def decode_call(<<169, 5, 156, 187>> <> _ = calldata) do
    _signature = hex!("0xa9059cbb")
    {:ok, "transfer", decode_transfer_call(calldata)}
  end

  def decode_call(<<35, 184, 114, 221>> <> _ = calldata) do
    _signature = hex!("0x23b872dd")
    {:ok, "transferFrom", decode_transfer_from_call(calldata)}
  end

  def decode_call(_) do
    :not_found
  end

  @doc false
  @spec decode_event(term(), term()) :: term()
  def decode_event(
        [
          <<140, 91, 225, 229, 235, 236, 125, 91, 209, 79, 113, 66, 125, 30, 132, 243, 221, 3, 20, 192, 247, 178, 41, 30,
            91, 32, 10, 200, 199, 195, 185, 37>>
          | _
        ] = topics,
        data
      ) do
    decode_approval_event(topics, data)
  end

  def decode_event(
        [
          <<221, 242, 82, 173, 27, 226, 200, 155, 105, 194, 176, 104, 252, 55, 141, 170, 149, 43, 167, 241, 99, 196, 161,
            22, 40, 245, 90, 77, 245, 35, 179, 239>>
          | _
        ] = topics,
        data
      ) do
    decode_transfer_ddf252ad_event(topics, data)
  end

  def decode_event(_, _) do
    :not_found
  end

  @doc false
  @spec decode_error(term()) :: term()
  def decode_error(_) do
    if true do
      :not_found
    else
      {:ok, "Impossible", <<>>}
    end
  end
end
